### ISSUE TITLE
Kan geen patroon vinden

### ISSUE THREAD

**Issue by vinnie1234** [HAN-ASD-DT/complexity-assignment-vinnie1234#1]
Is er iemand die mij kan helpen een patroon te vinden? Een hint is al genoeg zodat ik daarna verder kan met een formule hierna vinden

**Comment by dvberkel** [comment]
Als mensen jouw willen helpen, dan moet jij wat meer context bieden.

Welk probleem heb jij onderzocht? Wat heb jij al gedaan? Wat zijn jouw resultaten? Wat voor vermoedens heb jij?

**Comment by Dewinster** [comment]
Gebruik je de tm machine gegeven door Daan of die van jezelf?

**Comment by vinnie1234** [comment]
Verschil is verschil is de 1e keer een verdubbeling daarna geen zichtbaar patroon
Er is geen verdubbeling tussen de verschillen te zien. Ook dit lijkt zonder een patroon
Verschil van vorige bij de huidige optellen levert niet de nieuwe op, dit geld ook voor het verschil van het verschil

Mijn vermoeden ligt toch dat er een patroon is in het verschil van het verschil, maar het kan dus zijn dat ik me daar volledig vast kijk.

@dewinster: die van daan, dat zou er boven moeten staan?

**Comment by dvberkel** [comment]
De *in case of an emergency*-TM is ook een lastige om te analyseren. Het moet immers een uitdaging blijven om een :1st_place_medal: te verdienen.

@vinnie1234 Heb jij al een idee wat de TM berekend? Misschien helpt dat om een inzicht te krijgen.

**Comment by dvberkel** [comment]
En om makkelijk inzicht te krijgen in de verschillen van de verschiilen kun jij wellicht een spreadsheet maken.

**Comment by vinnie1234** [comment]
@dvberkel ik neem aan Turing Machine?

**Comment by dvberkel** [comment]
Nope, ik bedoel een spreadsheet, zodat jij de verschil van verschillen makkelijker kunt bepalen

**Comment by vinnie1234** [comment]
Excuses, ik las betekend in plaats van berekend. 

Maar nee ik heb geen idee wat die berekend. Ik straks even alles in een spreaksheet zetten, misschien wordt het daar inderdaad duidelijker van, je hoort van.

**Comment by vinnie1234** [comment]
Ik heb even geprobeerd te zoeken wat er nou precies gebeurd, het lijkt er op dat er antwoord is N + (N+1).

Kan dit kloppen? Heb mijn excel geupdate in mijn reposetory.
Maar hier kom ik helaas nog niet verder mee...

**Comment by dvberkel** [comment]
Je hebt jezelf niet zo scherp geformuleerd, maar het klopt dat de antwoorden de reeks van [Fibonacci](https://en.wikipedia.org/wiki/Fibonacci_number) is.

Zoals in het college besproken groeit deze reeks heel hard (exponentieel) dus de Turing Machine heeft voor het opschrijven van het antwoord al een hoop stappen nodig.
